/** Mirrors SchoolPaymentGatewayResponse — non-secret facts only. The Security code and Connection
 * URL never appear here; they come only from the password-gated setup flow (SchoolPaymentSetupDetails). */
export type PaymentGatewayStatus = 'PENDING' | 'ACTIVE' | 'RETIRED' | 'REJECTED';

/** Where a school's online fee payments go right now (OnlinePaymentRoutingService.RouteType). */
export type OnlinePaymentRoute = 'SCHOOL_GATEWAY' | 'PLATFORM_FALLBACK' | 'UNAVAILABLE';

export interface SchoolPaymentGateway {
  id: number;
  schoolId: number;
  schoolName: string | null;
  provider: string;
  maskedKeyId: string;
  liveMode: boolean;
  status: PaymentGatewayStatus;
  submittedBy: string | null;
  submittedAt: string | null;
  verifiedAt: string | null;
  activatedAt: string | null;
  activatedBy: string | null;
  retiredAt: string | null;
  rejectedAt: string | null;
  statusReason: string | null;
  lastWebhookAt: string | null;
  /** When the school admin said they finished the Razorpay-side setup (their claim; unverifiable). */
  setupConfirmedAt: string | null;
}

export interface SchoolPaymentGatewayOverview {
  route: OnlinePaymentRoute;
  platformFallbackUntil: string | null;
  requireLiveKeys: boolean;
  encryptionConfigured: boolean;
  gateways: SchoolPaymentGateway[];
}

/** The Security code is generated by Edunexify — the school never chooses it. */
export interface SchoolPaymentGatewaySubmitRequest {
  keyId: string;
  keySecret: string;
  currentPassword: string;
}

/** What the admin pastes into Razorpay: returned once on submission and again only with the
 * current password (never cached, never in the overview). */
export interface SchoolPaymentSetupDetails {
  gatewayId: number;
  connectionUrl: string;
  securityCode: string;
  razorpayEvents: string[];
}

export interface SchoolPaymentGatewaySubmitResponse {
  gateway: SchoolPaymentGateway;
  setup: SchoolPaymentSetupDetails;
}
