import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, takeUntil } from 'rxjs';
import { PaymentGatewayService } from '../../services/payment-gateway.service';
import { AuthStateService } from '../../auth/auth-state.service';
import { ToastService } from '../../services/toast.service';
import { LoggerService } from '../../services/logger.service';
import {
  SchoolPaymentGateway,
  SchoolPaymentGatewayOverview,
  SchoolPaymentSetupDetails,
} from '../../interfaces/payment-gateway';

/** What the school admin sees on School Settings → Payments, in school-friendly terms. */
export type ConnectionState =
  | 'unavailable'      // setup can't be started right now (server encryption not configured)
  | 'not-connected'
  | 'finish-setup'     // keys verified, Razorpay-side setup not confirmed yet
  | 'waiting'          // setup confirmed, waiting for Edunexify approval
  | 'connected';

export type WizardStep = 1 | 2 | 3 | 4;

/**
 * "Connect Razorpay": a guided wizard for non-technical school admins. Razorpay credentials (step 2)
 * and the Edunexify password (step 3) live in separate forms so password managers never mistake the
 * Key ID for a username. The Security code is generated by Edunexify and only ever shown here —
 * once after verification, or again after re-entering the password.
 */
@Component({
  selector: 'app-school-payment-connection',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './school-payment-connection.component.html',
  styleUrl: './school-payment-connection.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SchoolPaymentConnectionComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  static readonly RAZORPAY_DASHBOARD_URL = 'https://dashboard.razorpay.com/';
  readonly razorpayDashboardUrl = SchoolPaymentConnectionComponent.RAZORPAY_DASHBOARD_URL;
  private static readonly KEY_ID = /^rzp_(live|test)_[A-Za-z0-9]{8,40}$/;

  overview: SchoolPaymentGatewayOverview | null = null;
  loading = false;
  loadFailed = false;

  /** Wizard (connecting a new account). null = not in the wizard. */
  step: WizardStep | null = null;
  keyId = '';
  keySecret = '';
  showKeySecret = false;
  password = '';
  verifying = false;
  stepError: string | null = null;

  /** Step 4 content, and whether it was opened from an existing connection (re-display). */
  setup: SchoolPaymentSetupDetails | null = null;
  setupForGatewayId: number | null = null;
  showSecurityCode = false;
  confirming = false;

  /** Password prompt before showing the setup details again. */
  revealFor: SchoolPaymentGateway | null = null;
  revealPassword = '';
  revealing = false;
  revealError: string | null = null;

  /** Fallback when the browser can't mask a text field: the secret is then shown as typed. */
  readonly canMaskText = typeof CSS !== 'undefined' && !!CSS.supports?.('-webkit-text-security', 'disc');

  constructor(
    private gatewayService: PaymentGatewayService,
    private authState: AuthStateService,
    private toast: ToastService,
    private logger: LoggerService,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit(): void {
    this.load();
  }

  ngOnDestroy(): void {
    this.clearSecrets();
    this.destroy$.next();
    this.destroy$.complete();
  }

  /** Lets the password manager associate the password with the right account (never shown). */
  get username(): string {
    return this.authState.getUser()?.userId ?? '';
  }

  load(): void {
    this.loading = true;
    this.loadFailed = false;
    this.cdr.markForCheck();
    this.gatewayService.getOverview().pipe(takeUntil(this.destroy$)).subscribe({
      next: (overview) => {
        this.overview = overview;
        this.loading = false;
        this.cdr.markForCheck();
      },
      error: (e) => {
        this.logger.error('Failed to load the Razorpay connection', e);
        this.loading = false;
        this.loadFailed = true;
        this.cdr.markForCheck();
      },
    });
  }

  // ── derived state ─────────────────────────────────────────────────────────

  get connected(): SchoolPaymentGateway | null {
    return this.overview?.gateways.find(g => g.status === 'ACTIVE') ?? null;
  }

  get waiting(): SchoolPaymentGateway | null {
    return this.overview?.gateways.find(g => g.status === 'PENDING') ?? null;
  }

  /** The latest request, if Edunexify declined it (a superseded request is never the latest). */
  get notApproved(): SchoolPaymentGateway | null {
    const latest = this.overview?.gateways[0];
    return latest && latest.status === 'REJECTED' ? latest : null;
  }

  get state(): ConnectionState {
    if (this.connected) return 'connected';
    const waiting = this.waiting;
    if (waiting) return waiting.setupConfirmedAt ? 'waiting' : 'finish-setup';
    if (this.overview && !this.overview.encryptionConfigured) return 'unavailable';
    return 'not-connected';
  }

  get usingTemporaryEdunexifyAccount(): boolean {
    return this.overview?.route === 'PLATFORM_FALLBACK' && !this.connected;
  }

  /** "Working" once a payment confirmation has arrived; otherwise not yet (normal before the first payment). */
  get confirmationsWorking(): boolean {
    return !!this.connected?.lastWebhookAt;
  }

  // ── wizard ────────────────────────────────────────────────────────────────

  startWizard(): void {
    this.clearSecrets();
    this.stepError = null;
    this.step = 1;
    this.cdr.markForCheck();
  }

  cancelWizard(): void {
    this.clearSecrets();
    this.step = null;
    this.stepError = null;
    this.cdr.markForCheck();
  }

  back(): void {
    if (this.step === 2) this.step = 1;
    else if (this.step === 3) { this.password = ''; this.step = 2; }
    this.stepError = null;
    this.cdr.markForCheck();
  }

  ready(): void {
    this.step = 2;
    this.cdr.markForCheck();
  }

  /** Step 2 → 3: only format checks here; Razorpay itself checks the pair in step 3. */
  continueFromKeys(): void {
    const keyId = this.keyId.trim();
    if (!keyId || !this.keySecret.trim()) {
      this.stepError = 'Paste both the Key ID and the Key Secret from Razorpay.';
    } else if (!SchoolPaymentConnectionComponent.KEY_ID.test(keyId)) {
      this.stepError = 'That doesn\'t look like a Razorpay Key ID. It starts with rzp_live_.';
    } else if (this.overview?.requireLiveKeys && keyId.startsWith('rzp_test_')) {
      this.stepError = 'This is a test key. In Razorpay, switch to Live mode and generate a Live key.';
    } else {
      this.stepError = null;
      this.step = 3;
    }
    this.cdr.markForCheck();
  }

  verify(): void {
    if (!this.password) {
      this.stepError = 'Enter your Edunexify password.';
      this.cdr.markForCheck();
      return;
    }
    this.verifying = true;
    this.stepError = null;
    this.cdr.markForCheck();
    this.gatewayService.submit({
      keyId: this.keyId.trim(),
      keySecret: this.keySecret.trim(),
      currentPassword: this.password,
    }).pipe(takeUntil(this.destroy$)).subscribe({
      next: (res) => {
        this.clearSecrets();
        this.verifying = false;
        this.setup = res.setup;
        this.setupForGatewayId = res.gateway.id;
        this.step = 4;
        this.load();
      },
      error: (e) => {
        this.logger.error('Razorpay account verification failed', e);
        this.password = '';
        this.verifying = false;
        // A wrong password keeps the keys so only the password is retyped; anything Razorpay
        // refused sends the admin back to the keys.
        this.stepError = this.serverMessage(e) || 'We couldn\'t verify your Razorpay account. Please try again.';
        if (e?.status !== 403) {
          this.keySecret = '';
          this.step = 2;
        }
        this.cdr.markForCheck();
      },
    });
  }

  completeSetup(): void {
    const id = this.setupForGatewayId;
    if (id == null) return;
    const gateway = this.overview?.gateways.find(g => g.id === id);
    if (gateway?.status === 'ACTIVE') {
      // Re-display for an already connected account: nothing to confirm.
      this.closeSetup();
      return;
    }
    this.confirming = true;
    this.cdr.markForCheck();
    this.gatewayService.confirmSetup(id).pipe(takeUntil(this.destroy$)).subscribe({
      next: () => {
        this.confirming = false;
        this.closeSetup();
        this.toast.success('Thank you', 'We\'ll review your Razorpay connection and let you know when online payments are on.');
        this.load();
      },
      error: (e) => {
        this.logger.error('Failed to record Razorpay setup', e);
        this.confirming = false;
        this.toast.error('Not saved', this.serverMessage(e) || 'Please try again.');
        this.cdr.markForCheck();
      },
    });
  }

  /** Leave step 4 without confirming ("do this later"). */
  closeSetup(): void {
    this.setup = null;
    this.setupForGatewayId = null;
    this.showSecurityCode = false;
    this.step = null;
    this.cdr.markForCheck();
  }

  // ── showing the setup again (password each time) ─────────────────────────

  askToReveal(gateway: SchoolPaymentGateway): void {
    this.revealFor = gateway;
    this.revealPassword = '';
    this.revealError = null;
    this.cdr.markForCheck();
  }

  cancelReveal(): void {
    this.revealFor = null;
    this.revealPassword = '';
    this.revealError = null;
    this.cdr.markForCheck();
  }

  reveal(): void {
    const gateway = this.revealFor;
    if (!gateway) return;
    if (!this.revealPassword) {
      this.revealError = 'Enter your Edunexify password.';
      this.cdr.markForCheck();
      return;
    }
    this.revealing = true;
    this.revealError = null;
    this.cdr.markForCheck();
    this.gatewayService.getSetupDetails(gateway.id, this.revealPassword).pipe(takeUntil(this.destroy$)).subscribe({
      next: (details) => {
        this.revealing = false;
        this.revealPassword = '';
        this.revealFor = null;
        this.setup = details;
        this.setupForGatewayId = gateway.id;
        this.showSecurityCode = false;
        this.step = 4;
        this.cdr.markForCheck();
      },
      error: (e) => {
        this.revealing = false;
        this.revealPassword = '';
        this.revealError = this.serverMessage(e) || 'Please try again.';
        this.cdr.markForCheck();
      },
    });
  }

  copy(value: string, what: string): void {
    try {
      navigator.clipboard.writeText(value).then(
        () => this.toast.success('Copied', `${what} copied.`),
        () => this.toast.info('Copy manually', `Select the ${what.toLowerCase()} and copy it.`));
    } catch {
      this.toast.info('Copy manually', `Select the ${what.toLowerCase()} and copy it.`);
    }
  }

  private clearSecrets(): void {
    this.keyId = '';
    this.keySecret = '';
    this.password = '';
    this.revealPassword = '';
    this.showKeySecret = false;
    this.setup = null;
    this.setupForGatewayId = null;
    this.showSecurityCode = false;
  }

  private serverMessage(e: any): string | null {
    const body = e?.error;
    const msg = typeof body === 'string' ? body : (body?.message || body?.error);
    return typeof msg === 'string' && msg.length < 300 ? msg : null;
  }
}
